# Generated by Django 3.2.10 on 2025-08-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gulf_central', '0002_alter_news_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='slug',
        ),
    ]
