# Generated by Django 3.2.10 on 2025-09-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gulf_central', '0003_auto_20250831_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Flexible Pricing Plans', help_text='Main title for the pricing section', max_length=255)),
                ('description', models.TextField(blank=True, default='Choose from our tailored plans designed to meet your business needs.', help_text='Short description under the title')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Plan name (e.g., Starter, Standard, Pro)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short tagline for the plan')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='gulf_central.pricingsection')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Feature description', max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='gulf_central.pricingplan')),
            ],
        ),
    ]
