# Generated by Django 3.2.10 on 2025-09-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gulf_central', '0004_planfeature_pricingplan_pricingsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='text',
            field=models.CharField(help_text='Feature description (Admin can add any number of features)', max_length=255),
        ),
    ]
