# Generated by Django 3.2.10 on 2025-09-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gulf_central', '0005_alter_planfeature_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCalculatorEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_activity', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('sponsorship', models.CharField(blank=True, max_length=10, null=True)),
                ('owners', models.CharField(max_length=50)),
                ('visas', models.CharField(max_length=10)),
                ('office_required', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
