# Generated by Django 3.2.10 on 2025-09-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gulf_central', '0006_costcalculatorenquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costcalculatorenquiry',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='costcalculatorenquiry',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='costcalculatorenquiry',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='costcalculatorenquiry',
            name='office_required',
            field=models.CharField(max_length=10),
        ),
    ]
