# Generated by Django 3.2.10 on 2025-09-14 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gulf_central', '0009_auto_20250914_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceenquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
