# Generated by Django 3.2.10 on 2025-09-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gulf_central', '0012_clientlogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
