# Generated by Django 4.2.6 on 2025-09-18 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gulf_central", "0016_auto_20250915_1634"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "setup_type",
                    models.CharField(
                        choices=[
                            ("mainland", "Mainland Company Setup"),
                            ("freezone", "Freezone Company Setup"),
                            ("offshore", "Offshore Company Setup"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
